### ISSUE TITLE
Butonul de submit: nu schimba cursorul atunci cand mouse-ul este deasupra lui.

### ISSUE THREAD

**Issue by StoianCatalin** [ASII-Organization/databaseupdate#1]
Atunci cand suntem pe butonul de submit ("Trimite") cu mouse-ul culoarea se schimba ceea ce e foarte bine insa ma asteptam sa se schimbe si cursorul in "pointer" ca sa imi arate ca acel buton este clickable.

**Comment by BocaBogdan** [comment]
Gata
